---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template will create the VMs and initialize them with necessary configuration
              to deploy the k8s cluster using KubeSpray Distribution'
Parameters:
  NetworkStackName:
    Description: Name of an active CloudFormation stack that contains the networking
      resources, such as the subnet and security group, that will be used in this
      stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: sympan-ha-vpc-stack

Resources:
### Security Groups
  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "node-sg"
      GroupDescription: "Security Group for K8S Node"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-VPC-ID"

  AllowAllPortsInboundRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt NodeSecurityGroup.GroupId
      IpProtocol: '-1'
      CidrIp: '0.0.0.0/0'

### Nodes
  MASTER1:
    DependsOn:
      - NodeSecurityGroup
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3a.small
      KeyName: 'sympn-kp'
      SourceDestCheck: 'false'
      ImageId: 'ami-02d55cb47e83a99a0'
      NetworkInterfaces:
        - GroupSet:
            - Ref: NodeSecurityGroup
          AssociatePublicIpAddress: 'true'
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${NetworkStackName}-PUBLIC-SUB1-ID"
      Tags:
        - Key: Name
          Value: master-1
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            - - "#!/bin/bash\n"
              - sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
              - sudo sed -i 's/.*ssh-rsa/ssh-rsa/g' /root/.ssh/authorized_keys
              - sudo systemctl restart sshd.service
  MASTER2:
    DependsOn:
      - NodeSecurityGroup
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3a.small
      KeyName: 'sympn-kp'
      SourceDestCheck: 'false'
      ImageId: 'ami-02d55cb47e83a99a0'
      NetworkInterfaces:
        - GroupSet:
            - Ref: NodeSecurityGroup
          AssociatePublicIpAddress: 'true'
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${NetworkStackName}-PUBLIC-SUB2-ID"
      Tags:
        - Key: Name
          Value: master-2
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            - - "#!/bin/bash\n"
              - sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
              - sudo sed -i 's/.*ssh-rsa/ssh-rsa/g' /root/.ssh/authorized_keys
              - sudo systemctl restart sshd.service

  WORKER1:
    DependsOn:
      - NodeSecurityGroup
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3a.small
      KeyName: 'sympn-kp'
      SourceDestCheck: 'false'
      ImageId: 'ami-02d55cb47e83a99a0'
      NetworkInterfaces:
        - GroupSet:
            - Ref: NodeSecurityGroup
          AssociatePublicIpAddress: 'true'
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${NetworkStackName}-PUBLIC-SUB1-ID"
      Tags:
        - Key: Name
          Value: worker-1
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            - - "#!/bin/bash\n"
              - sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
              - sudo sed -i 's/.*ssh-rsa/ssh-rsa/g' /root/.ssh/authorized_keys
              - sudo systemctl restart sshd.service

  WORKER2:
    DependsOn:
      - NodeSecurityGroup
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3a.small
      KeyName: 'sympn-kp'
      SourceDestCheck: 'false'
      ImageId: 'ami-02d55cb47e83a99a0'
      NetworkInterfaces:
        - GroupSet:
            - Ref: NodeSecurityGroup
          AssociatePublicIpAddress: 'true'
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${NetworkStackName}-PUBLIC-SUB2-ID"
      Tags:
        - Key: Name
          Value: worker-2
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            - - "#!/bin/bash\n"
              - sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
              - sudo sed -i 's/.*ssh-rsa/ssh-rsa/g' /root/.ssh/authorized_keys
              - sudo systemctl restart sshd.service